name: cipsy
favicon: null
layout_spectrum: 0
typography_spectrum: 0.57161
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#b96100'
    - '#b0cbd2'
    - '#fcf703'
  brandStrength: 0.8229306722059846
  lightness: 0.39222584548406303
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
